- name: My first play
  hosts: saphosts
  tasks:
   - name: Ping my hosts
     ansible.builtin.ping:
   - name: Print message
     ansible.builtin.debug:
       msg: Hello world
   - name: Return all secrets from a path
     debug:
       msg: "{{ lookup('community.hashi_vault.vault_kv2_get', 'secret=secrets/qc-one/qsb/000 token=hvs.1yWlrPDUcBstmHEid25ieE5N url=http://192.168.50.30:8200')}}"

