- name: My first play
  hosts: saphosts
  tasks:
   - name: Ping my hosts
     ansible.builtin.ping:
   - name: Print message
     ansible.builtin.debug:
       msg: Hello world
   - name: Return all secrets from a path
      ansible.builtin.debug:
       msg: "{{ lookup('hashi_vault', 'secret=secrets/QC-one token=hvs.1yWlrPDUcBstmHEid25ieE5N url=http://192.168.50.30:8200')}}"

