- name: My first play
  hosts: saphosts
  tasks:
   - name: Ping my hosts
     ansible.builtin.ping:
   - name: Print message
     ansible.builtin.debug:
       msg: Hello world
   - name: Read the latest version of a kv2 secret from Vault via the remote host with userpass auth
     community.hashi_vault.vault_kv2_get:
       url: http://192.168.50.30:8200
       token: hvs.1yWlrPDUcBstmHEid25ieE5N 
       path: QC-one/SAP/QC1
      register: response
    - name: Display the results
      ansible.builtin.debug:
        msg:
        - "Secret: {{ response.secret }}"
        - "Data: {{ response.data }}"
        - "Metadata: {{ response.metadata }}"
        - "Full response: {{ response.raw }}"
        - "Value of key 'password' in the secret: {{ response.secret.password }}"
  # equivalent API path is secret/data/hello
  # - name: Return all secrets from a path
  #   debug:
  #     msg: "{{ lookup('community.hashi_vault.vault_kv2_get', 'secret=secrets/qc-one/qsb/000 token=hvs.1yWlrPDUcBstmHEid25ieE5N url=http://192.168.50.30:8200')}}"

