- name: My second play
  hosts: localhost
  tasks:
   - name: Return all secrets from a path
     debug:
      msg: "{{ lookup('hashi_vault', 'secret=QC-one/data/QSB token=hvs.CAESIIc2ziOoXhC84mxFyuV4KMdHUGkOWCl6Bl727pAYL5D1Gh4KHGh2cy5xUDBKc2VLY2pEbzR1R0lyTDV4eHF4dEg url=http://192.168.50.30:8200')}}"
