- name: My second play
  hosts: localhost
  tasks:
   - name: Return all secrets from a path
     debug:
      msg: "{{ lookup('community.hashi_vault.hashi_vault', 'QC-one/data/SAP/QCS token=hvs.1yWlrPDUcBstmHEid25ieE5N url=http://192.168.50.30:8200')}}"